# Generated by Django 3.2 on 2021-05-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0012_auto_20191025_1852"),
    ]

    operations = [
    ]